Fix build error with java because of env variable JAVA_TOOL_OPTIONS
ycm-core/ycmd pull request #1469
Opened 2020-08-28 13:27 UTC by Borwe

There is an error one gets when building for java completions while having environment variable of JAVA_TOOL_OPTIONS, the value of that env will be printed and it's not an int, so we get errors. Made it such that the value of JAVA_TOOL_OPTIONS get saved into a variable and then cleared from env until we execute and get the version, then we reset the JAVA_TOOL_OPTIONS.

2020-08-28 13:41 UTC, bstaletic commented
Hey, thanks for the pull request.

I actually encountered this in #1468, but I'm happy to merge this separately.

You don't actually need to restore the value, as nothing in the process of the`build.py` script depends on it or runs java.

My approach was to modify a copied environment.

2020-08-28 21:05 UTC, bstaletic commented
Flake8 error:

```
/home/vsts/work/1/s/build.py:969:20: E225 missing whitespace around operator
/home/vsts/work/1/s/build.py:969:31: YCM201 exactly one space required after (
/home/vsts/work/1/s/build.py:969:50: YCM202 exactly one space required before )
/home/vsts/work/1/s/build.py:971:6: YCM201 exactly one space required after (
/home/vsts/work/1/s/build.py:971:35: YCM202 exactly one space required before )
/home/vsts/work/1/s/build.py:972:7: YCM112 expected an indented block of 4 spaces
/home/vsts/work/1/s/build.py:972:19: YCM201 exactly one space required after (
/home/vsts/work/1/s/build.py:972:38: YCM202 exactly one space required before )
/home/vsts/work/1/s/build.py:983:14: YCM201 exactly one space required after [
/home/vsts/work/1/s/build.py:983:33: YCM202 exactly one space required before ]
/home/vsts/work/1/s/build.py:983:34: E225 missing whitespace around operator
```

2020-08-29 12:11 UTC, Borwe commented
> Flake8 error:
> 
> ```
> /home/vsts/work/1/s/build.py:969:20: E225 missing whitespace around operator
> /home/vsts/work/1/s/build.py:969:31: YCM201 exactly one space required after (
> /home/vsts/work/1/s/build.py:969:50: YCM202 exactly one space required before )
> /home/vsts/work/1/s/build.py:971:6: YCM201 exactly one space required after (
> /home/vsts/work/1/s/build.py:971:35: YCM202 exactly one space required before )
> /home/vsts/work/1/s/build.py:972:7: YCM112 expected an indented block of 4 spaces
> /home/vsts/work/1/s/build.py:972:19: YCM201 exactly one space required after (
> /home/vsts/work/1/s/build.py:972:38: YCM202 exactly one space required before )
> /home/vsts/work/1/s/build.py:983:14: YCM201 exactly one space required after [
> /home/vsts/work/1/s/build.py:983:33: YCM202 exactly one space required before ]
> /home/vsts/work/1/s/build.py:983:34: E225 missing whitespace around operator
> ```

LOL! but it compiles. 😅

2020-08-29 12:24 UTC, puremourning commented
Yeah we have a strict coding style, and we have a flake8 extension to enforce it.

2020-08-29 12:30 UTC, Borwe commented
> Yeah we have a strict coding style, and we have a flake8 extension to enforce it.

Is there some command inside YCM that can auto Flake 8 code?

2020-08-29 12:34 UTC, puremourning commented
pip install --user -r test_requirements.txt
flake8 build.py

2020-08-29 12:35 UTC, puremourning commented
It's also run by `./run_tests.py`

2020-08-29 13:48 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1469)* status: 0 of 2 LGTMs obtained (waiting on @Borwe)

___
*[build.py, line 971 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1469#-MFuSaFu0uWPiZf1Gpx5:-MFuSaFu0uWPiZf1Gpx6:b-3ayn6i) ([raw file](https://github.com/ycm-core/ycmd/blob/7158be8f8842e247be11204d6ce99dcc162092a1/build.py#L971)):*
> ```Python
>   java_tool_options = os.getenv( 'JAVA_TOOL_OPTIONS' )
> 
>   if( java_tool_options is not None ):
> ```

no parentheses. `if java_tool_options is not None`
___
*[build.py, line 972 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1469#-MFuTCdo3taBkfscUpj4:-MFuTCdo3taBkfscUpj5:b-q80frm) ([raw file](https://github.com/ycm-core/ycmd/blob/7158be8f8842e247be11204d6ce99dcc162092a1/build.py#L972)):*
> ```Python
> 
>   if( java_tool_options is not None ):
>       os.unsetenv( 'JAVA_TOOL_OPTIONS' )
> ```

this isn't available on Windows

https://docs.python.org/3/library/os.html#os.unsetenv

prefer to do what @bstaletic  did .e.g

```
new_env = os.environ.copy()
try:
  new_env.pop( 'JAVA_TOOL_OPTIONS' )
except KeyError:
  pass
```

then pass `new_env` to `check_output( ... ., env = new_env )`


<!-- Sent from Reviewable.io -->

2020-09-09 16:57 UTC, bstaletic commented
@Borwe Once again, thanks for the PR. This was fixed in #1472

2020-09-09 16:57 UTC, closed without merging