[READY] Support generating a port when connecting to LS over TCP
ycm-core/ycmd pull request #1482
Opened 2020-10-05 17:16 UTC by puremourning

In the scenario where we are starting the server then connecting to it
over TCP, it makes sense to use an unused local port, rather than
requiring the user hard-code one in their configuration.

This change allows the Generic LSP config to set 'port' to '*' in which
case an unused local port is selected and used. The selected port is
made available to the 'cmdline' as '${port}'.

This is needed to support the new PHP completer in a better way.

2020-10-10 19:03 UTC, bstaletic requested changes
`GoToSymbol` flaked on Winblows... again.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1482#-:-MJItLC65QbzRVJIEk4W:b-rvp7yt)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[README.md, line 281 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIrOyh85WPScLx0Br6:-MJIrOyh85WPScLx0Br7:bnkgdu5) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/README.md#L281)):*
> ```Markdown
> - `cmdline`: the list representing the command line to execute the server
>   (optional; mandatory if port not specified)
> - `port`: optional. If specified, a TCL connection is used to this port. If set
> ```

s/TCL/TCP ?
___
*[README.md, line 301 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIr_M09Zbd3omOnIek:-MJIr_M09Zbd3omOnIel:brhun0a) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/README.md#L301)):*
> ```Markdown
> ```
> 
> Or, to use a TCL connection:
> ```

Same here?
___
*[ycmd/completers/language_server/language_server_completer.py, line 1611 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIswSs6Y9u15BacCP4:-MJIswSt52q-OQO-kT62:b-8w1fu8) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/ycmd/completers/language_server/language_server_completer.py#L1611)):*
> ```Python
>       extras = self.CommonDebugItems() + self.ExtraDebugItems( request_data )
>       logfiles = [ self._stdout_file,
>                    self._stderr_file ] + self.AdditionalLogFiles()
> ```

In case of standard I/O, `self._stdout_file` is `None`. That means it's going to show up in debug info as `None`, which probably isn't what we want.


<!-- Sent from Reviewable.io -->

2020-10-12 19:19 UTC, puremourning reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1482)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[README.md, line 281 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIrOyh85WPScLx0Br6:-MJTEd724JBnjfzsA45e:b-pbi8nm) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/README.md#L281)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

s/TCL/TCP ?
</blockquote></details>

LOL I write too much TCL code!

Done.
___
*[README.md, line 301 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIr_M09Zbd3omOnIek:-MJTEgo32Ibejb4rOUVT:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/README.md#L301)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

Done.
___
*[ycmd/completers/language_server/language_server_completer.py, line 1611 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1482#-MJIswSs6Y9u15BacCP4:-MJTEiys3iyAlBFzVKA_:b-1diqjr) ([raw file](https://github.com/ycm-core/ycmd/blob/be1016c42b6cc83378f2db675105c015f86fd350/ycmd/completers/language_server/language_server_completer.py#L1611)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

In case of standard I/O, `self._stdout_file` is `None`. That means it's going to show up in debug info as `None`, which probably isn't what we want.
</blockquote></details>

I thought this too, but it seems that it's ok for it to be None. It doesn't show up in the client, in the same way that stderr isn't checked for None here - we don't display logs when they are None. (null) 


<!-- Sent from Reviewable.io -->

2020-10-12 19:59 UTC, bstaletic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1482#-:-MJTLMyyBmOteQ6tP-DK:bnfp4nl)* status: 1 of 2 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-12 20:43 UTC, puremourning reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1482#-:-MJTYKoa68mzpD9xbkVF:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-12 20:43 UTC, merged