[READY] Switch to C++17
ycm-core/ycmd pull request #1489
Opened 2020-10-24 12:00 UTC by bstaletic

List of changes:

- Switch to C++17
- Use `string_view` where appropriate
- Allow shared lock ownership
- Avoid raw new, with `make_unique`
- Avoid `shared_ptr` in the identifier database
- Do not show valgrind 'possibly lost' leak errors
- Avoid AST deserialization errors in libclang/clangd tests

The BoostParts removal is left out because it kills Reviewable.

2020-10-24 13:14 UTC, puremourning requested changes
> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPdx-838AL6gm0EPbs:b-dl8cx3) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
> ```CMake
> set( CPP17_AVAILABLE false )
> if ( CMAKE_COMPILER_IS_GNUCXX )
>   if ( NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9 )
> ```

gcc 8 supports c++17. that's the compiler I use. so we need to support that _for certain_ :)

looks like gcc 7 is enough: https://gcc.gnu.org/projects/cxx-status.html
___
*[cpp/CMakeLists.txt, line 220 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeLW4CnKbBs0Erjga:-MKPeLW4CnKbBs0Erjgb:b-nwjv23) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L220)):*
> ```CMake
>     "In order to use this application, you require a more modern compiler "
>     "than the default compiler on this platform. "
>     "Please install the devtoolset-6 or greater. For example, see this link: "
> ```

devtoolset-8
___
*[cpp/CMakeLists.txt, line 221 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeQfz0aEJ33kzcaDD:-MKPeQfz0aEJ33kzcaDE:b-y5u62q) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L221)):*
> ```CMake
>     "than the default compiler on this platform. "
>     "Please install the devtoolset-6 or greater. For example, see this link: "
>     "https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/" )
> ```

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/
___
*[cpp/CMakeLists.txt, line 224 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeT1V3R7IGD1TSbpN:-MKPeT1V3R7IGD1TSbpO:bjoazir) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L224)):*
> ```CMake
> 
>     # Finally, just check if it is installed and they just need to activate it.
>     if ( EXISTS /opt/rh/devtoolset-6 )
> ```

/opt/rh/devtoolset-8
___
*[cpp/CMakeLists.txt, line 226 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeYWVACpdi6SOJASI:-MKPeYWVACpdi6SOJASJ:bz64udt) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L226)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       message( STATUS "NOTE: It looks like you have the devtoolset-6 "
>                       "installed in /opt/rh/devtoolset-6, so you probably "
>                       "just need to activate it and re-run the installation. "
>                       "For example: source /opt/rh/devtoolset-6/enable")
> ```
</details>


-6 -> -8
___
*[cpp/ycm/CandidateRepository.cpp, line 79 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPfxi-6UtXrgzaLVe6:-MKPfxi-6UtXrgzaLVe7:b-31d7fd) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CandidateRepository.cpp#L79)):*
> ```cpp
> 
> void CandidateRepository::ClearCandidates() {
>   candidate_holder_.clear();
> ```

shouldn't this be done under the lock ?
___
*[cpp/ycm/CharacterRepository.cpp, line 64 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPgC6mDf_LEjegFb1b:-MKPgC6mDf_LEjegFb1c:bwyr7xz) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CharacterRepository.cpp#L64)):*
> ```cpp
> 
> void CharacterRepository::ClearCharacters() {
>   character_holder_.clear();
> ```

also here, are we missing a lock acquire?
___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKPggSt8NRvnh_k3tBJ:b8612r) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
> ```cpp
> 
> CodePoint::CodePoint( std::string_view code_point )
>   : CodePoint( FindCodePoint( code_point.data() ) ) {
> ```

do we need to pass len to FindCodePoint now ? Or should we change it to take a string_view ?

I mean, we _know_ that the incoming string is null terminated right, but in future, it might not be now that we're using a range.
___
*[cpp/ycm/CodePointRepository.cpp, line 63 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPh1Ba7029nn0fEwq3:-MKPh1Ba7029nn0fEwq4:b-yq3btr) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePointRepository.cpp#L63)):*
> ```cpp
> 
> void CodePointRepository::ClearCodePoints() {
>   code_point_holder_.clear();
> ```

and here?
___
*[cpp/ycm/IdentifierCompleter.cpp, line 58 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPhQhiEHMnidHqw7DW:-MKPhQhj5ZN0xgiuXShC:b-oj84wu) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierCompleter.cpp#L58)):*
> ```cpp
>   std::string& filetype,
>   std::string& filepath ) {
>   identifier_database_.ClearCandidatesStoredForFile( std::string( filetype ),
> ```

seems such a shame to copy these then move them :/
___
*[cpp/ycm/IdentifierCompleter.cpp, line 70 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPhkOQ8xL38I5S6HmJ:-MKPhkOQ8xL38I5S6HmK:blscqy2) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierCompleter.cpp#L70)):*
> ```cpp
>   for( auto&& path : absolute_paths_to_tag_files ) {
>     identifier_database_.AddIdentifiers(
>       ExtractIdentifiersFromTagsFile( std::move( path ) ) );
> ```

are we really ok to take ownership and reset these string s?

It looks like they come from the python layer:


```
  def _AddIdentifiersFromTagFiles( self, tag_files ):
    absolute_paths_to_tag_files = ycm_core.StringVector()
    for tag_file in self._FilterUnchangedTagFiles( tag_files ):
      absolute_paths_to_tag_files.append( tag_file )

    if not absolute_paths_to_tag_files:
      return

    self._completer.AddIdentifiersToDatabaseFromTagFiles(
      absolute_paths_to_tag_files )

```

are we sure this is safe ? what would happen if we used `absolute_paths_to_tag_files` in the python code after this? safe ?
___
*[cpp/ycm/IdentifierDatabase.cpp, line 42 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPiGKf7V8VmGGcC0qT:-MKPiGKf7V8VmGGcC0qU:b-q1jbbb) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierDatabase.cpp#L42)):*
> ```cpp
>   for ( auto&& filetype_and_map : filetype_identifier_map ) {
>     for ( auto&& filepath_and_identifiers : filetype_and_map.second ) {
>       auto filetype = filetype_and_map.first;
> ```

again are we sure that we can move this ?


<!-- Sent from Reviewable.io -->

2020-10-24 13:28 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @micbou and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPkhZNAb8PIPOCkDAU:b-pwlp6w) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

gcc 8 supports c++17. that's the compiler I use. so we need to support that _for certain_ :)

looks like gcc 7 is enough: https://gcc.gnu.org/projects/cxx-status.html
</blockquote></details>

`<filesystem>` is a problem on gcc 8. It works, but requires `-lstdc++fs`.

We could also support clang 7, but that also requires a special flag, this time `-lstdc++fs` if using libstdc++, else `-lc++fs` if using libc++...

I'm just not sure how to do this correctly.
___
*[cpp/CMakeLists.txt, line 220 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeLW4CnKbBs0Erjga:-MKPlPzK2vbpi2LL6V2q:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L220)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

devtoolset-8
</blockquote></details>

Done.
___
*[cpp/CMakeLists.txt, line 221 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeQfz0aEJ33kzcaDD:-MKPlQVuBXUqBr6xLHzw:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L221)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/
</blockquote></details>

Done.
___
*[cpp/CMakeLists.txt, line 224 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeT1V3R7IGD1TSbpN:-MKPlRpp1F8OsqKzP6Ut:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L224)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

/opt/rh/devtoolset-8
</blockquote></details>

Done.
___
*[cpp/CMakeLists.txt, line 226 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPeYWVACpdi6SOJASI:-MKPlSXl9wwTnm8cbtyO:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L226)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> ```
>       message( STATUS "NOTE: It looks like you have the devtoolset-6 "
>                       "installed in /opt/rh/devtoolset-6, so you probably "
>                       "just need to activate it and re-run the installation. "
>                       "For example: source /opt/rh/devtoolset-6/enable")
> ```

-6 -> -8
</blockquote></details>

Done.
___
*[cpp/ycm/CandidateRepository.cpp, line 79 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPfxi-6UtXrgzaLVe6:-MKPlUTH8KrvEsaSmavu:b-enov5f) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CandidateRepository.cpp#L79)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

shouldn't this be done under the lock ?
</blockquote></details>

Check the header. `ClearFoo()` is exposed only for C++ tests and C++ tests are single threaded.

@micbou was against taking a lock here, but I'm fine with it. Do you want me to change it?
___
*[cpp/ycm/CharacterRepository.cpp, line 64 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPgC6mDf_LEjegFb1b:-MKPlijlCzjzs1a1VANE:b9s4eza) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CharacterRepository.cpp#L64)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

also here, are we missing a lock acquire?
</blockquote></details>

Same thing. Only for tests, which are single-threadded.
___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKPm0vq89dx_-XehmG5:bmkhzx) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

do we need to pass len to FindCodePoint now ? Or should we change it to take a string_view ?

I mean, we _know_ that the incoming string is null terminated right, but in future, it might not be now that we're using a range.
</blockquote></details>

We're not using the length anywhere. We're using the C API that expects NULL terminated strings. I agree that this is questionable, so I'm fine with whatever you think is most appropriate.
___
*[cpp/ycm/CodePointRepository.cpp, line 63 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPh1Ba7029nn0fEwq3:-MKPmLI-0Y9uzXF_fB_y:b-ex0u0z) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePointRepository.cpp#L63)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

and here?
</blockquote></details>

Yeah, tests, single thread, not quite necessary. 
___
*[cpp/ycm/IdentifierCompleter.cpp, line 58 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPhQhiEHMnidHqw7DW:-MKPmTYE9rNyXWOdOybH:b-mi0r40) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierCompleter.cpp#L58)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

seems such a shame to copy these then move them :/
</blockquote></details>

I should look into this...
___
*[cpp/ycm/IdentifierCompleter.cpp, line 70 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPhkOQ8xL38I5S6HmJ:-MKPmffB39Q2wWdLUGiM:b-3ln36n) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierCompleter.cpp#L70)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

are we really ok to take ownership and reset these string s?

It looks like they come from the python layer:


```
  def _AddIdentifiersFromTagFiles( self, tag_files ):
    absolute_paths_to_tag_files = ycm_core.StringVector()
    for tag_file in self._FilterUnchangedTagFiles( tag_files ):
      absolute_paths_to_tag_files.append( tag_file )

    if not absolute_paths_to_tag_files:
      return

    self._completer.AddIdentifiersToDatabaseFromTagFiles(
      absolute_paths_to_tag_files )

```

are we sure this is safe ? what would happen if we used `absolute_paths_to_tag_files` in the python code after this? safe ?
</blockquote></details>

Pybind11 copies the python string into `std::string`. So we're stealing a copy python is providing us with.
___
*[cpp/ycm/IdentifierDatabase.cpp, line 42 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPiGKf7V8VmGGcC0qT:-MKPmrc309TpV-05U_vx:bmg5qpj) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierDatabase.cpp#L42)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

again are we sure that we can move this ?
</blockquote></details>

Same thing. Pybind makes a copy for us.


<!-- Sent from Reviewable.io -->

2020-10-24 13:40 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @micbou and @puremourning)

___
*[cpp/ycm/IdentifierCompleter.cpp, line 58 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPhQhiEHMnidHqw7DW:-MKPoc1i8LGdnfoEVyJz:b-jnrenw) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/IdentifierCompleter.cpp#L58)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I should look into this...
</blockquote></details>

Looked. Here's the thing - this just makes the copy explicit. It was there previously.

We can't move directly, because we need to use path twice.

I would love to be able to take `std::string&&` from pybind and move that, but... that is for a future version of pybind11.


<!-- Sent from Reviewable.io -->

2020-10-24 13:45 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @micbou, and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPpQz-72Y99KVMBwOz:b3i0k91) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`<filesystem>` is a problem on gcc 8. It works, but requires `-lstdc++fs`.

We could also support clang 7, but that also requires a special flag, this time `-lstdc++fs` if using libstdc++, else `-lc++fs` if using libc++...

I'm just not sure how to do this correctly.
</blockquote></details>

```
if ( CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8 )
   // error
else's( CMAKE_CSS_COMPILER_VERSION VERSION_LESS 9 )
   // ok
   // add link flag `-lstdc++fs`
else()
  // OK
endif()
```

can this work ? we use `-lstdc++fs` at work with devtoolset-8.

I'm fine with requiring clang 8. with PRs welcome to support clang 7.

lots of RHEL/centos users will have gcc8 as the devtoolset-9 is very new (like this year I think). gcc 9 is also pretty new (like 1.5y or something).


<!-- Sent from Reviewable.io -->

2020-10-24 13:52 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @micbou and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPrlFK4_MsLjcAnB4V:bs28xna) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

```
if ( CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8 )
   // error
else's( CMAKE_CSS_COMPILER_VERSION VERSION_LESS 9 )
   // ok
   // add link flag `-lstdc++fs`
else()
  // OK
endif()
```

can this work ? we use `-lstdc++fs` at work with devtoolset-8.

I'm fine with requiring clang 8. with PRs welcome to support clang 7.

lots of RHEL/centos users will have gcc8 as the devtoolset-9 is very new (like this year I think). gcc 9 is also pretty new (like 1.5y or something).
</blockquote></details>

What concerns me is the combination of clang + libstdc++.

If clang is new, but libstdc++ came with gcc 8, we still need to add `-lstdc++fs`. Can we check the standard library name?


<!-- Sent from Reviewable.io -->

2020-10-24 13:54 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @micbou, and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPsccq58AvubuY62eQ:buu6j39) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

What concerns me is the combination of clang + libstdc++.

If clang is new, but libstdc++ came with gcc 8, we still need to add `-lstdc++fs`. Can we check the standard library name?
</blockquote></details>

hmmm good point. that's true anyway with the clang version.

with auto tools we would do a test compile. does cmake have an equivalent ?


<!-- Sent from Reviewable.io -->

2020-10-24 13:54 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @micbou, and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPt-EYEgBEiraO-rkw:b-u5nhg8) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

hmmm good point. that's true anyway with the clang version.

with auto tools we would do a test compile. does cmake have an equivalent ?
</blockquote></details>

https://stackoverflow.com/questions/54290254/problem-adding-stdfilesystem-to-cmake-project


<!-- Sent from Reviewable.io -->

2020-10-24 13:59 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @micbou and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPtV_Q4w_2MzXLYxvU:b-5a15r1) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/54290254/problem-adding-stdfilesystem-to-cmake-project
</blockquote></details>

CMake does have a test compile feature and I've done it before for Cquery, while it was still actively developed.

I still don't know what I should check for.

As for that SO answer, it's only concerned with libstdc++'s `-lstdc++fs` and they are using cmake 3.12, while our cmake still requires 2.8.


<!-- Sent from Reviewable.io -->

2020-10-24 14:01 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @micbou and @puremourning)

___
*[cpp/CMakeLists.txt, line 166 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPdx-838AL6gm0EPbr:-MKPuQgK4wBCE0LhWYOH:b-j3riwr) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/CMakeLists.txt#L166)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

CMake does have a test compile feature and I've done it before for Cquery, while it was still actively developed.

I still don't know what I should check for.

As for that SO answer, it's only concerned with libstdc++'s `-lstdc++fs` and they are using cmake 3.12, while our cmake still requires 2.8.
</blockquote></details>

https://github.com/jacobdufault/cquery/pull/775/files


<!-- Sent from Reviewable.io -->

2020-10-24 22:01 UTC, puremourning requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/ycm/CandidateRepository.cpp, line 79 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPfxi-6UtXrgzaLVe6:-MKRcJ3t2YGEAL646o6X:b2ni8ds) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CandidateRepository.cpp#L79)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Check the header. `ClearFoo()` is exposed only for C++ tests and C++ tests are single threaded.

@micbou was against taking a lock here, but I'm fine with it. Do you want me to change it?
</blockquote></details>

nah
___
*[cpp/ycm/CMakeLists.txt, line 320 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRblvQ8d1u-BgPvE3D:-MKRblvRCblLWjfrqOdo:bdnkj4h) ([raw file](https://github.com/ycm-core/ycmd/blob/bc9c759ad05f4416457cfb4ae16e7562aae2c8cf/cpp/ycm/CMakeLists.txt#L320)):*
> ```CMake
> if( NOT MSVC )
>   file( WRITE ${CMAKE_CURRENT_BINARY_DIR}/main.cpp "#include <filesystem>\nint main( int argc, char ** argv ) {\n  std::filesystem::path p( argv[ 0 ] );\n  return p.string().length();\n}" )
>   try_compile( STD_FS_NO_LIB_NEEDED ${CMAKE_CURRENT_BINARY_DIR} SOURCES ${CMAKE_CURRENT_BINARY_DIR}/main.cpp COMPILE_DEFINITIONS -std=c++17 )
> ```

can we break this and the other lines at 80 characters so it is a bit more readable ?
___
*[cpp/ycm/CMakeLists.txt, line 352 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRbrIT8B5qF8UKJQxe:-MKRbrIT8B5qF8UKJQxf:b-qq5nuq) ([raw file](https://github.com/ycm-core/ycmd/blob/bc9c759ad05f4416457cfb4ae16e7562aae2c8cf/cpp/ycm/CMakeLists.txt#L352)):*
> ```CMake
>                        ${PYTHON_LIBRARIES}
>                        ${LIBCLANG_TARGET}
> 		       ${STD_FS_LIB}
> ```

is that... a .... *pukes* .. is that a TAB I see before me ?
___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKRbygZ4CRQ7rl6NJkj:biw2p1b) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

We're not using the length anywhere. We're using the C API that expects NULL terminated strings. I agree that this is questionable, so I'm fine with whatever you think is most appropriate.
</blockquote></details>

it does seem wonky to me to just use the data elem of a string_view, but I think this is probably fine. we'll know soon enough is we break it.


<!-- Sent from Reviewable.io -->

2020-10-24 22:23 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

___
*[cpp/ycm/CMakeLists.txt, line 325 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRhBQU2WWs_STABt7c:-MKRhBQU2WWs_STABt7d:b19gfk5) ([raw file](https://github.com/ycm-core/ycmd/blob/5ef271360dbc61ad9b49c5b06535442030134fd6/cpp/ycm/CMakeLists.txt#L325)):*
> ```CMake
>   file( REMOVE ${CMAKE_CURRENT_BINARY_DIR}/main.cpp )
> else()
>   set( STD_FS_NO_LIB_NEEDED TRUE )
> ```

invert this if()

```
if( MSVC )
  set( STD_FS_NO_LIB_NEEDED TRUE )
else()

endif()
```


<!-- Sent from Reviewable.io -->

2020-10-24 22:24 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a couple of minor prettifications.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489#-:-MKRhSyk5MlUacNiuLR3:b-5oz8p8)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2020-10-24 22:33 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)

___
*[cpp/ycm/CMakeLists.txt, line 320 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRblvQ8d1u-BgPvE3D:-MKRintP0TOXuxWg4ENw:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/bc9c759ad05f4416457cfb4ae16e7562aae2c8cf/cpp/ycm/CMakeLists.txt#L320)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

can we break this and the other lines at 80 characters so it is a bit more readable ?
</blockquote></details>

Done.
___
*[cpp/ycm/CMakeLists.txt, line 352 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRbrIT8B5qF8UKJQxe:-MKRiAT07JLJx4dhKZel:b-91igkd) ([raw file](https://github.com/ycm-core/ycmd/blob/bc9c759ad05f4416457cfb4ae16e7562aae2c8cf/cpp/ycm/CMakeLists.txt#L352)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

is that... a .... *pukes* .. is that a TAB I see before me ?
</blockquote></details>

Two... Two tabs.
___
*[cpp/ycm/CMakeLists.txt, line 325 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKRhBQU2WWs_STABt7c:-MKRixo2-w6fjhCozMjB:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/5ef271360dbc61ad9b49c5b06535442030134fd6/cpp/ycm/CMakeLists.txt#L325)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

invert this if()

```
if( MSVC )
  set( STD_FS_NO_LIB_NEEDED TRUE )
else()

endif()
```
</blockquote></details>

Done.
___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKRjKtj95MjRFFF-LLx:boea3qq) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

it does seem wonky to me to just use the data elem of a string_view, but I think this is probably fine. we'll know soon enough is we break it.
</blockquote></details>

Last chance to tell me to change it?


<!-- Sent from Reviewable.io -->

2020-10-25 08:28 UTC, puremourning reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKTrolyAhkoGGHZpAG9:biaump) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Last chance to tell me to change it?
</blockquote></details>

How complex is it to change? Like if it’s a rabbit hole don’t bother but if it’s trivial let’s do it. 


<!-- Sent from Reviewable.io -->

2020-10-25 09:52 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[cpp/ycm/CodePoint.cpp, line 84 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKPggSt8NRvnh_k3tBI:-MKTwp7p2MH77DEVyJv8:b-l8qkmt) ([raw file](https://github.com/ycm-core/ycmd/blob/9d1daf142855a6495eef49afbedb4553f2a8b765/cpp/ycm/CodePoint.cpp#L84)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

How complex is it to change? Like if it’s a rabbit hole don’t bother but if it’s trivial let’s do it. 
</blockquote></details>

Not very complex. I think I got the code to be pretty clean. It does result in more assembly, but it wasn't reflected in our benchmarks beyong a margin of error.
___
*[cpp/ycm/CodePoint.cpp, line 63 at r6](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKU8HCT7WJObANfRRhR:-MKU8HCT7WJObANfRRhS:b5vs9e0) ([raw file](https://github.com/ycm-core/ycmd/blob/f8f3a71ad248a6207fbb8ed21bb780270b19d776/cpp/ycm/CodePoint.cpp#L63)):*
> ```cpp
>     text,
>     []( const char* cp, std::string_view text ) {
>       return text.compare( cp ) > 0;
> ```

Note that we used to do `cp <=> text < 0`. Now we're doing `text <=> cp > 0`.

The obvious first thought is "that should obviously be `>=`", but no. This change isn't about negating the comparison, it's about multiplying the inequasion by `-1`. Besides math, I do have tests to back this up.

Why did I write it like this? Because I thought the following was even more confusing:

    return -1 * text.compare( cp ) < 0;

We can't do `cp.compare( text ) < 0;` because `cp` is `const char*` and comes from that giant Unicode table. We can't change `code_points.original` to hold `std::string_view[]`, because it would blow up the binary size, the size on HDD *and* would make every known compiler stall. We *can* can change `cp` to `std::string_view` in the lambda, but I'm not sure what would be the benefit.


<!-- Sent from Reviewable.io -->

2020-10-25 10:24 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[cpp/ycm/CodePoint.cpp, line 63 at r6](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKU8HCT7WJObANfRRhR:-MKUGs-K1jDaiht_E-FC:bfmut0o) ([raw file](https://github.com/ycm-core/ycmd/blob/f8f3a71ad248a6207fbb8ed21bb780270b19d776/cpp/ycm/CodePoint.cpp#L63)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Note that we used to do `cp <=> text < 0`. Now we're doing `text <=> cp > 0`.

The obvious first thought is "that should obviously be `>=`", but no. This change isn't about negating the comparison, it's about multiplying the inequasion by `-1`. Besides math, I do have tests to back this up.

Why did I write it like this? Because I thought the following was even more confusing:

    return -1 * text.compare( cp ) < 0;

We can't do `cp.compare( text ) < 0;` because `cp` is `const char*` and comes from that giant Unicode table. We can't change `code_points.original` to hold `std::string_view[]`, because it would blow up the binary size, the size on HDD *and* would make every known compiler stall. We *can* can change `cp` to `std::string_view` in the lambda, but I'm not sure what would be the benefit.
</blockquote></details>

Looking at the code for `string_view::compare(CharT*)`:

```c++
      compare(const _CharT* __str) const noexcept
      { return this->compare(basic_string_view{__str}); }
```

So we can use `std::string_view cp` here. It will be exactly the same.


<!-- Sent from Reviewable.io -->

2020-10-25 13:24 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[cpp/ycm/CodePoint.cpp, line 63 at r6](https://reviewable.io/reviews/ycm-core/ycmd/1489#-MKU8HCT7WJObANfRRhR:-MKUvBsd3xJkep17AnDm:b-ssu0a) ([raw file](https://github.com/ycm-core/ycmd/blob/f8f3a71ad248a6207fbb8ed21bb780270b19d776/cpp/ycm/CodePoint.cpp#L63)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Looking at the code for `string_view::compare(CharT*)`:

```c++
      compare(const _CharT* __str) const noexcept
      { return this->compare(basic_string_view{__str}); }
```

So we can use `std::string_view cp` here. It will be exactly the same.
</blockquote></details>

Wait... not that we have a `std::string_view`, we can just compare `cp < text`, which is just `std::less{}`, which is also the default comparison for `lower_bound`, so we can completely avoid the lambda. I'll do this after my compiler finishes with llvm.


<!-- Sent from Reviewable.io -->

2020-10-25 14:47 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1489#-:-MKVDVP0C0gRL1ZQ2g8p:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2020-10-25 17:11 UTC, bstaletic commented
:lgtm:

2020-10-25 17:12 UTC, merged