[READY] Remove completer_utils._MatchesSematicTrigger
ycm-core/ycmd pull request #1503
Opened 2020-11-15 22:34 UTC by bstaletic

It's almost a shame to remove something with 10x more tests than code, but it's not used anywhere.

2020-11-15 22:43 UTC, puremourning commented
Just to be sure, this isn’t used by the client is It?

2020-11-15 22:47 UTC, bstaletic commented
Already checked and it isn't used by YCM.

On Sun, 15 Nov 2020, 23:43 Ben Jackson, <notifications@github.com> wrote:

> Just to be sure, this isn’t used by the client is It?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ycm-core/ycmd/pull/1503#issuecomment-727650169>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3OIU4MQM5AX4UYNK7I2JTSQBKRNANCNFSM4TWPAYKQ>
> .
>

2020-11-15 22:49 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1503)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/tests/completer_utils_test.py, line 74 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1503#-MMD5GRT4VQ1NvLmG7Qt:-MMD5GRT4VQ1NvLmG7Qu:b-rhhlnb) ([raw file](https://github.com/ycm-core/ycmd/blob/fe8f5d0ccacfa860698ff920b93bcf06fc722c42/ycmd/tests/completer_utils_test.py#L74)):*
> ```Python
> 
> 
> def MatchesSemanticTrigger_Basic_test():
> ```

Are all of these cases covered by equivalent tests for _MatchingSemanticTrigger?


<!-- Sent from Reviewable.io -->

2020-11-16 08:41 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1503)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/tests/completer_utils_test.py, line 74 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1503#-MMD5GRT4VQ1NvLmG7Qt:-MMFCgrR6ZSDit5oeQKz:birxyxh) ([raw file](https://github.com/ycm-core/ycmd/blob/fe8f5d0ccacfa860698ff920b93bcf06fc722c42/ycmd/tests/completer_utils_test.py#L74)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Are all of these cases covered by equivalent tests for _MatchingSemanticTrigger?
</blockquote></details>

Good point. I believe that is the case now.


<!-- Sent from Reviewable.io -->

2020-11-16 14:55 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1503#-:-MMGYKdJ5AHpNIcbuBxu:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2020-11-16 15:16 UTC, bstaletic commented
:lgtm:

2020-11-16 15:16 UTC, merged