[READY] Refactor cmake files and require cmake 3.14
ycm-core/ycmd pull request #1513
Opened 2020-12-11 20:08 UTC by bstaletic

Cmake deprecated support for cmake2 and RHEL7 has cmake 3.14 available.
Besides that, the `FindPythonLibs.cmake` is also replaced with `FindPython3.cmake`, because the former is also deprecated.

With cmake3, it's possible to not use `CMAKE_CXX_FLAGS` global variable and stick to target based commands. This is what I've done for the most part. The only file that doesn't fit this is the top level `cpp/CMakeLists.txt`.

One thing to note, regarding `target_whatever()` are all the `PUBLIC`/`INTERFACE`/`PRIVATE` modifiers. Here's what they mean:

- `PRIVATE` - the dependency is "local" to the specified target. Targets that depend on this target don't have the specified dependency.
- `INTERFACE` - the specified dependency is not directly applied to the specified target. However, targets that depend on this target also depend on the specified dependency.
- `PUBLIC` - the dependency is applied to the specified target. Also, every target that depends on this target also depends on the specified dependency.

There's probably more stuff that can be cleaned up, but this seems to work so far.

2020-12-19 19:29 UTC, puremourning requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[build.py, line 358 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwGlNw2jCLpdorExfZ:-MOwGlNw2jCLpdorExf_:b-cz8oj2) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/build.py#L358)):*
> ```Python
> 
>   return [
>     f'-DPython3_LIBRARY={ python_library }',
> ```

We probably need to update the "Full installation guide" for this ?
___
*[build.py, line 488 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwHK6J7oKxGktAP3lF:-MOwHK6J7oKxGktAP3lG:ba7wyco) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/build.py#L488)):*
> ```Python
>   cmake = PathToFirstExistingExecutable( cmake_exe )
>   if cmake is None:
>     sys.exit( "ERROR: Unable to find cmake executable. "
> ```

maybe include `in any of { cmake_exe }` ?
___
*[cpp/CMakeLists.txt, line 197 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwRoRC0GTN5q-Qa4lf:-MOwRoRC0GTN5q-Qa4lg:bgs137b) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/CMakeLists.txt#L197)):*
> ```CMake
> set( CMAKE_CXX_EXTENSIONS OFF )
> if ( CPP17_AVAILABLE )
>   # Cygwin needs its hand held a bit; see issue #473
> ```

do we still need this comment ? is it still relevant?
___
*[cpp/ycm/CMakeLists.txt, line 374 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwSfwYBtS0N-IuTT0Z:-MOwSfwYBtS0N-IuTT0_:b-yeknwt) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/ycm/CMakeLists.txt#L374)):*
> ```CMake
>   OUTPUT_STRIP_TRAILING_WHITESPACE )
> set_target_properties( ${PROJECT_NAME} PROPERTIES
> 			PREFIX ""
> ```

are those... tabs?
___
*[cpp/ycm/tests/CMakeLists.txt, line 64 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwTLHADDD49pbPzAtL:-MOwTLHADDD49pbPzAtM:b-fs62ey) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/ycm/tests/CMakeLists.txt#L64)):*
> ```CMake
> target_include_directories(
>   ${PROJECT_NAME}
>   PRIVATE ${ycm_core_SOURCE_DIR}/../whereami )
> ```

what's this `../whereami` do ?


<!-- Sent from Reviewable.io -->

2020-12-19 21:11 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[build.py, line 358 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwGlNw2jCLpdorExfZ:-MOwmoetBqrbKpWgq9eX:bedcr62) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/build.py#L358)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

We probably need to update the "Full installation guide" for this ?
</blockquote></details>

The full installation guide doesn't mention even the old `-DPYTHON_FOO`. I'm not against updating it, for the record, just not sure how.
___
*[build.py, line 488 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwHK6J7oKxGktAP3lF:-MOwmRvz5t6Lor69X1vU:b-8af5j0) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/build.py#L488)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

maybe include `in any of { cmake_exe }` ?
</blockquote></details>

I'm not sure what you mean by that.
___
*[cpp/CMakeLists.txt, line 197 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwRoRC0GTN5q-Qa4lf:-MOwnXjW5uZh-gDwkupZ:by3nux9) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/CMakeLists.txt#L197)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

do we still need this comment ? is it still relevant?
</blockquote></details>

http://cygwin.1069669.n5.nabble.com/snprintf-with-g-std-c-98-error-snprintf-was-not-declared-in-this-scope-td27135.html

Seems like it only affected the C++98/C++0x era. `vsnprintf` and `snprintf` came with C99, which is after C++98...

Removed.
___
*[cpp/ycm/CMakeLists.txt, line 374 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwSfwYBtS0N-IuTT0Z:-MOwosjiCc_bMaz1wIAh:b9qaxdo) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/ycm/CMakeLists.txt#L374)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

are those... tabs?
</blockquote></details>

I was sure I got rid of them... My bad...
___
*[cpp/ycm/tests/CMakeLists.txt, line 64 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwTLHADDD49pbPzAtL:-MOwp1Tw8_L0IkmawNNp:bdaaj0b) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/cpp/ycm/tests/CMakeLists.txt#L64)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what's this `../whereami` do ?
</blockquote></details>

It lives in `cpp/whereami`. It's a C library that portably tells us the full path to the `ycm_core_tests` executable/directory. This is then used to find the path to `testdata`.

Eons ago, I was annoyed about having to `cd` instead of just running `./build/ycm/tests/ycm_core_tests`, because the `testdata` was relative to cwd.


<!-- Sent from Reviewable.io -->

2020-12-30 17:02 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513#-:-MPoaM7W8vZs1qrk9Ed3:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[build.py, line 488 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1513#-MOwHK6J7oKxGktAP3lF:-MPoa4Iv1YTVL-AM7VAP:b-ouqdax) ([raw file](https://github.com/ycm-core/ycmd/blob/b0c624cbb3c3e839884583e3f34e30bc8eb062fa/build.py#L488)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

I'm not sure what you mean by that.
</blockquote></details>

sorry I meant the message could say "Unable to find cmake executable in any of (list of paths checked)"

Optional.


<!-- Sent from Reviewable.io -->

2020-12-30 18:48 UTC, bstaletic reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513#-:-MPoyiAh5YXQ2WIwzaVc:bnfp4nl)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2020-12-30 21:00 UTC, puremourning approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2020-12-30 21:01 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1513#-:-MPpS34pCVjMytw_Sheq:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2020-12-31 08:23 UTC, merged

2020-12-31 18:04 UTC, henryiii commented
Was about to complain about this warning, glad to see it has been fixed!

```
CMake Deprecation Warning at ycm/CMakeLists.txt:18 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```