Fix Standard library includes with Xcode 12.5
ycm-core/ycmd pull request #1569
Opened 2021-05-12 17:21 UTC by puremourning

Previously the "platform" didn't include the standard library, so we
always ended up using the standard library from the "toolchain". As of
12.5 the platform includes a copy of the standard library which leads to
2 incompatible ones being included. This leads to lots of errors.

Solution is to only use one or t'other, preferring the platform one.

2021-05-12 17:56 UTC, bstaletic commented
Libclang `flags_test.py` is failing. Looks like we end up missing `-isystem /usr/include/c++/v1` from the flags. Was that intentional?

2021-05-16 12:15 UTC, jchrys commented
this change fixes issue on my device. thanks for pointing this out.

2021-05-17 18:46 UTC, puremourning reviewed
Fixed the tests.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1569#-:-M_vddyrAm2MW1nQ_URD:b-379xbn)* status: 0 of 2 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-05-17 19:36 UTC, puremourning reviewed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1569)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2021-05-17 19:40 UTC, bstaletic requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1569)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[third_party/generic_server/package.json, line 60 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_voG7F5Q1CVKBZZqAD:-M_voG7F5Q1CVKBZZqAE:b-k74s9u) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/third_party/generic_server/package.json#L60)):*
> ```JSON
> 		"@typescript-eslint/parser": "^2.3.0",
> 		"eslint": "^6.4.0",
> 		"mocha": "^8.1.1",
> ```

Did you change this? Was it intentional?
___
*[third_party/generic_server/server/package-lock.json, line 1 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_vpoXkDulef4gWbR_L:-M_vpoXkDulef4gWbR_M:b-1nidbb) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/third_party/generic_server/server/package-lock.json#L1)):*
> ```JSON
> {
> ```

Are these `package-lock.json` things even supposed to be committed?
___
*[ycmd/completers/cpp/flags.py, line 558 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_vpNeN9AbMuht2L-yT:-M_vpNeN9AbMuht2L-yU:b3pei9p) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/ycmd/completers/cpp/flags.py#L558)):*
> ```Python
>     if os.path.exists( platform_stdlib ):
>       flags.extend( [ '-isystem', platform_stdlib ] )
>     elif toolchain:
> ```

Do we want the else here? Previously, if `toolchain` was true, we'd add both `toolchain/usr/include/c++/v1` and `sysroot/usr/include/c++/v1`. I get that it can be seen as weird to add both, but just wanted to double check.


<!-- Sent from Reviewable.io -->

2021-05-17 20:49 UTC, puremourning reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1569)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[third_party/generic_server/package.json, line 60 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_voG7F5Q1CVKBZZqAD:-M_w4NK9Det8T236sFST:b5cruwf) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/third_party/generic_server/package.json#L60)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Did you change this? Was it intentional?
</blockquote></details>

I just updated it because that's what run_tests.py does and was left spamming in my client.
___
*[third_party/generic_server/server/package-lock.json, line 1 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_vpoXkDulef4gWbR_L:-M_w4W4L9Q5VLLbtVslj:b-wg6qac) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/third_party/generic_server/server/package-lock.json#L1)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Are these `package-lock.json` things even supposed to be committed?
</blockquote></details>

yes, they are, apparently
___
*[ycmd/completers/cpp/flags.py, line 558 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1569#-M_vpNeN9AbMuht2L-yT:-M_w4YV-C7QRsZGsbHEi:b-v1a185) ([raw file](https://github.com/ycm-core/ycmd/blob/df346430d75cd52d67db7c28d524947a62f2a65d/ycmd/completers/cpp/flags.py#L558)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do we want the else here? Previously, if `toolchain` was true, we'd add both `toolchain/usr/include/c++/v1` and `sysroot/usr/include/c++/v1`. I get that it can be seen as weird to add both, but just wanted to double check.
</blockquote></details>

the whole purpose of this change is _not_ to add both - that's what was causing the problem. Previously the first one (the sys root one) didn't exist, now it does so you end up with 2 incompatible stdlibs if you add both.


<!-- Sent from Reviewable.io -->

2021-05-17 21:22 UTC, bstaletic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1569#-:-M_wCFUgDXErlSdR69Pd:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2021-05-17 21:22 UTC, merged