Try to infer the latest MSVC version on windows like CMake Does
ycm-core/ycmd pull request #1626
Opened 2022-01-12 16:09 UTC by jmarrec

2022-01-12 16:11 UTC, jmarrec commented on build.py
> +                                '(default: %(default)s).' )
Not sure if I should raise or not...

2022-01-12 16:11 UTC, jmarrec commented on build.py
> +
This is what cmake does: # https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/cmGlobalVisualStudioGenerator.cxx#L201

2022-01-14 16:49 UTC, bstaletic requested changes
Please use reviewable for reviews, it's a lot nicer.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626#-:-MtOU79jCPpQ0yqTWPoJ:bvl06zg)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @jmarrec)

___
*[build.py, line 120 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOUW6b9606TrEu0-bS:-MtOUW6b9606TrEu0-bT:bpbyug7) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L120)):*
> ```Python
> def FindLatestMSVC():
>     import winreg
>     aReg = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
> ```

Variable names are snake case. Also `a` prefix makes zero sense to me.
___
*[build.py, line 123 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOTVJj0HifpKTxIlEt:-MtOTVJj0HifpKTxIlEu:b-umice4) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L123)):*
> ```Python
>     msvc = None
>     for i in [17, 16, 15]:
>         try:
> ```

    for i in range( 17, 14, -1 ):

That would work better.
___
*[build.py, line 125 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOTGYQ0mspQnGfXu3y:-MtOTGYQ0mspQnGfXu3z:b-m2qnl) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L125)):*
> ```Python
>         try:
>             aKey = winreg.OpenKey(aReg, rf'SOFTWARE\Microsoft\VisualStudio\{i}.0')
>             print(f"Found {i}")
> ```

Do we really want this `print()`? Even in the quiet build?
___
*[build.py, line 431 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtE2MccV0xTHa5edOOn-r1-431:-MtOTk0Q1MHXbtNAe31Y:bs5azcm) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L431)):*
<details><summary><i>Previously, jmarrec wrote…</i></summary><blockquote>

Not sure if I should raise or not...
</blockquote></details>

Perhaps only raise if `FindLatestMSVC()` returns `None` *and* `--msvc` wasn't supplied from the command line.


<!-- Sent from Reviewable.io -->

2022-01-17 09:49 UTC, jmarrec reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[build.py, line 120 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOUW6b9606TrEu0-bS:-MtbCRpH-gY-60rmMrMZ:b-ewm3yn) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L120)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Variable names are snake case. Also `a` prefix makes zero sense to me.
</blockquote></details>

I pawned the code block online. But yes, sure, will do snake case.
___
*[build.py, line 123 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOTVJj0HifpKTxIlEt:-MtbCgweEpMRUbOh0pln:b-zaqpdq) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L123)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

    for i in range( 17, 14, -1 ):

That would work better.
</blockquote></details>

I'm going to have to disagree here. We're talking about a 3 values list. The proposed change just obfuscates the intent.
___
*[build.py, line 125 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtOTGYQ0mspQnGfXu3y:-MtbCn_D8bLm_tV2bC-d:b-f2fexs) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L125)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do we really want this `print()`? Even in the quiet build?
</blockquote></details>

Probably not since you raised concerns :)
___
*[build.py, line 431 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1626#-MtE2MccV0xTHa5edOOn-r1-431:-MtbQj8x67bSvKbjsie4:b2ni9bh) ([raw file](https://github.com/ycm-core/ycmd/blob/fc5fb602abcbe26d1621461fa4ece13c39b6ad92/build.py#L431)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Perhaps only raise if `FindLatestMSVC()` returns `None` *and* `--msvc` wasn't supplied from the command line.
</blockquote></details>

ok.


<!-- Sent from Reviewable.io -->

2022-08-13 14:26 UTC, puremourning requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @jmarrec, and @puremourning)

___
*[`build.py` line 169 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1626#-N9MaFk05RpeoWxQpSCS:-N9MaFk05RpeoWxQpSCT:boixrw3) ([raw file](https://github.com/ycm-core/ycmd/blob/506672fac702ad5852837d26dd01d7b2d66580e1/build.py#L169)):*
> ```Python
>         if not quiet:
>           print(f"Found MSVC version {i}")
>           msvc = i
> ```

bug? it looks like his only happens if not quiet? or is that a rendering artefact in reviewable?


<!-- Sent from Reviewable.io -->

2022-08-13 15:06 UTC, puremourning commented
@MergifyIO rebase

2022-08-13 16:13 UTC, puremourning commented
ci is failing

2022-08-22 13:16 UTC, jmarrec reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

___
*[`build.py` line 169 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1626#-N9MaFk05RpeoWxQpSCS:-NA4gKZBAIasxuZZzCGU:b-mak8sd) ([raw file](https://github.com/ycm-core/ycmd/blob/506672fac702ad5852837d26dd01d7b2d66580e1/build.py#L169)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

bug? it looks like his only happens if not quiet? or is that a rendering artefact in reviewable?
</blockquote></details>

Yeah. I get **severely** confused with this python that doesn't conform to PEP 8 and uses 2 spaces instead of 4 spaces for indent.


<!-- Sent from Reviewable.io -->

2022-08-22 13:27 UTC, jmarrec commented
CI is failing because of styling issues. My entire vim setup is configured to follow PEP 8 and this styling is highly unusual. I'm going to take https://github.com/micbou/flake8-ycm for a spin and try to fix it.

2022-08-22 14:59 UTC, puremourning commented
The python style is not PEP8 by choice: from CONTRIBUTING.md.

![Screenshot 2022-08-22 at 15 57 08](https://user-images.githubusercontent.com/10584846/185952801-9e231040-3f48-4fe5-b8bc-2e07d01478f3.png)

This predates my involvement, but I stand by the choice; Val's style is much more readable (to me) than PEP8 would be. As you noticed we even have a flake8 plugin that will validate our style. I appreciate if you're used to another style, it's jarring though :D

2022-08-22 16:15 UTC, jmarrec commented
> > /home/runner/work/ycmd/ycmd/build.py:1:15: E999 SyntaxError: invalid syntax

Which runner is spitting this? I'm not seeing it locally... That's the shebang line too...

2022-08-22 16:17 UTC, puremourning commented
> > > /home/runner/work/ycmd/ycmd/build.py:1:15: E999 SyntaxError: invalid syntax
> 
> Which runner is spitting this? I'm not seeing it locally... That's the shebang line too...

Ugh, that's... omfg. I've approved the run again; fingers crossed.

Sometimes upstream changes in things like flake8 just break....

2022-08-22 16:18 UTC, puremourning commented
seeing this:

```
Run python3 benchmark.py --quiet
  File "<fstring>", line 1
    (latest_full_v=)
                  ^
SyntaxError: invalid syntax
```

2022-08-22 16:19 UTC, puremourning commented
Argh wth....

2022-08-22 16:20 UTC, jmarrec commented
> seeing this:
> 
> ```
> Run python3 benchmark.py --quiet
>   File "<fstring>", line 1
>     (latest_full_v=)
>                   ^
> SyntaxError: invalid syntax
> ```

https://github.com/ycm-core/ycmd/pull/1626/commits/3fae6955455abe0f43452c56e6fe0b092ede368f should fix it. Same issue, can't pass `--msvc` if not on windows anymore.

2022-08-22 16:27 UTC, jmarrec commented
I have Ubuntu 20.04, locally with https://github.com/ycm-core/ycmd/commit/3fae6955455abe0f43452c56e6fe0b092ede368f I can run benchmark.py just fine, despite what GHA is saying in https://github.com/ycm-core/ycmd/runs/7956426099?check_suite_focus=true ... I'm confused.

<details>
<summary>Click to expand local logs</summary>

```
(ycmd)julien@ycmd (infer_msvc_version=)$ python benchmark.py
Generating ycmd build configuration...OK
Compiling ycmd target: ycm_core...OK
Compiling ycmd target: ycm_core_benchmarks...OK
2022-08-22T18:21:04+02:00
Running /tmp/ycm_build_n95c1tq3/ycm/benchmarks/ycm_core_benchmarks
Run on (16 X 3600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 64 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 8192 KiB (x2)
Load Average: 5.90, 11.72, 12.25
------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                              Time             CPU   Iterations
------------------------------------------------------------------------------------------------------------------------
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/0                            598 ns          598 ns      1171383
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/0                          4259 ns         4257 ns       162846
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/0                        74652 ns        74623 ns         9533
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/0                     1146614 ns      1146068 ns          609
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/0                   24265345 ns     24247165 ns           28
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         23.14 NlgN      23.12 NlgN 
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              0 %             0 %    
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/10                           573 ns          573 ns      1213145
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/10                         3544 ns         3543 ns       198360
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/10                       40361 ns        40350 ns        17149
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/10                     644327 ns       643997 ns         1075
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/10                  12764358 ns     12751933 ns           56
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         12.18 NlgN      12.16 NlgN 
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              1 %             1 %    
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/0            2475 ns         2491 ns       280983
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/0          22939 ns        22975 ns        30796
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/0        356515 ns       356393 ns         2043
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/0      5477176 ns      5473803 ns          129
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/0    95884014 ns     95824835 ns            7
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        1462.58 N       1461.68 N    
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               1 %             1 %    
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/50           2494 ns         2513 ns       267024
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/50         22811 ns        22846 ns        30574
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/50       319981 ns       319819 ns         2193
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/50     4841900 ns      4839726 ns          133
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/50   82063849 ns     82007316 ns            8
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        1251.92 N       1251.06 N    
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               1 %             1 %    
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/0               781 ns          781 ns       905121
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/0             4741 ns         4739 ns       148847
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/0           82211 ns        82175 ns         8528
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/0        1262645 ns      1261902 ns          550
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/0      29401018 ns     29379464 ns           24
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            28.03 NlgN      28.01 NlgN 
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 1 %             1 %    
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/50              773 ns          772 ns       892480
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/50            5448 ns         5445 ns       118726
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/50          54031 ns        54005 ns        12884
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/50        811025 ns       810458 ns          859
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/50     16211577 ns     16194563 ns           44
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            15.46 NlgN      15.45 NlgN 
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 1 %             1 %    
Building regex module...OK
Building watchdog module...OK
```
</details>

2022-08-22 19:33 UTC, puremourning commented
I can't repro locally either, but I ran CI against master to check if it was a CI env issue, and that was OK. so _something_ about this patch is tripping up flake8 in GHA.. but only on linux/Mac...

2022-08-22 19:44 UTC, puremourning commented
OK I can repro locally with python 3.6.15 using pyenv.

```
ben@BeniMac2020 ycmd % ./run_tests.py
Running tests on Python 3.6.15

> lsp-sample@1.0.0 postinstall
> cd client && npm install && cd ../server && npm install && cd ..


up to date, audited 27 packages in 415ms

found 0 vulnerabilities

up to date, audited 6 packages in 410ms

found 0 vulnerabilities

up to date, audited 218 packages in 2s

30 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> lsp-sample@1.0.0 compile
> tsc -b

Running flake8
/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py:1:15: E999 SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./run_tests.py", line 390, in <module>
    Main()
  File "./run_tests.py", line 381, in Main
    RunFlake8()
  File "./run_tests.py", line 57, in RunFlake8
    subprocess.check_call( args )
  File "/Users/ben/.pyenv/versions/3.6.15/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ben/.pyenv/versions/3.6.15/Library/Frameworks/Python.framework/Versions/3.6/bin/python3', '-m', 'flake8', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/update_unicode.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/update_clang_headers.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/benchmark.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/run_tests.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/update_omnisharp.py', '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/update_api_docs.py']' returned non-zero exit status 1.
ben@BeniMac2020 ycmd %
```

2022-08-22 19:46 UTC, puremourning commented
what the actual...

```
ben@BeniMac2020 ycmd % python -m flake8 ycmd/ *.py
build.py:1:15: E999 SyntaxError: invalid syntax
ben@BeniMac2020 ycmd % python -m flake8 *.py
build.py:1:15: E999 SyntaxError: invalid syntax
ben@BeniMac2020 ycmd % python -m flake8 build.py
build.py:1:15: E999 SyntaxError: invalid syntax
ben@BeniMac2020 ycmd % which flake8
/Users/ben/Library/Python/3.9/bin/flake8
ben@BeniMac2020 ycmd % flake8 build.py
ben@BeniMac2020 ycmd % python -m flake8 build.py
build.py:1:15: E999 SyntaxError: invalid syntax
ben@BeniMac2020 ycmd %
```

2022-08-22 19:51 UTC, puremourning commented
this fixes is:

```diff
       except ValueError:
-        raise ValueError( "{latest_full_v=} is not a version number." )
+        raise ValueError( f"{latest_full_v} is not a version number." )

       if not quiet:
-        print( f'vswhere -latest returned version {latest_full_v=}' )
+        print( f'vswhere -latest returned version {latest_full_v}' )

       if latest_v not in ACCEPTABLE_VERSIONS:
         if latest_v > 17:
           if not quiet:
-            print( f'MSVC Version {latest_full_v=} is newer than expected.' )
+            print( f'MSVC Version {latest_full_v} is newer than expected.' )
         else:
           raise ValueError(
-            f'vswhere returned {latest_full_v=} which is unexpected.'
+            f'vswhere returned {latest_full_v} which is unexpected.'
             'Pass --msvc <version> argument.' )
       return latest_v
     else:
       if not quiet:
-        print( f'vswhere returned nothing usable, {latest_full_v=}' )
+        print( f'vswhere returned nothing usable, {latest_full_v}' )
```

Not sure what the `=` suffix does on the f-string, but python 3.6.15 doesn' support it so we can't use it.

2022-08-22 20:21 UTC, jmarrec commented
@puremourning this is embarassing since this is actually the second time I get bit by partial f-string support in earlier python 3.x. the "=" one was added in 3.8: https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

`f"{var=}"` is equivalent to `f"var={var}"`

2022-08-22 20:38 UTC, puremourning approved these changes
Thanks for the PR!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626#-:-NA6Gq-9Ap7mLzdUfdIa:b-mf999v)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2022-08-22 20:39 UTC, puremourning approved these changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1626)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic and @jmarrec)



<!-- Sent from Reviewable.io -->

2022-08-22 20:39 UTC, merged