msvc: Allow building with Visual Studio Preview versions
ycm-core/ycmd pull request #1711
Opened 2023-09-27 17:11 UTC by sankhesh

This change allows compiling ycmd against latest Visual Studio Preview versions.

Tested against Visual Studio 2022 Community version 17.8.2.0 Preview 2.0.

2023-09-27 19:36 UTC, bstaletic commented
Thanks for the pull request.
While I am not at all against this, I would like to know what `-prerelease` does.
Apologies, but I do not have a Windows machine handy.

2023-09-27 20:27 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711)* status: 0 of 2 LGTMs obtained (waiting on @sankhesh)

___
*[`build.py` line 129 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1711#-NfNJTH682ptyWAy7Yc4:-NfNJTH77B491e1xEWa-:bigjkvb) ([raw file](https://github.com/ycm-core/ycmd/blob/9c5317394360a6a258e79a29785a26eff588aa08/build.py#L129)):*
> ```Python
>       print( "Calling vswhere -latest -installationVersion" )
>     latest_full_v = subprocess.check_output(
>       [ VSWHERE_EXE, '-latest', '-prerelease', '-property', 'installationVersion' ]
> ```

Please can you explain canonically what this does? We don’t want to always use prerelease versions. In fact I’d rather not support them at all as we will never test with them. I’m happy to make it work by chance or by opt-in, but not by default. 


<!-- Sent from Reviewable.io -->

2023-09-27 20:35 UTC, sankhesh commented
With `-prerelease`,  `vswhere` also returns any prereleases/preview versions along with the release versions.
See doc: https://github.com/microsoft/vswhere/blob/f791b32483204ad3b0ff3cdce57a0c85ee119a8f/src/vswhere.lib/vswhere.lib.rc#L80

The current code defaults to the latest without user opt-in/choice if there are multiple versions. This change just extends it further to allow latest *Preview* versions as well. Note that without this change, if I just have VS Preview version installed (with valid MSVC compiler), ycmd build fails with the error that MSVC could not be found.

2023-09-27 20:45 UTC, puremourning commented
> With `-prerelease`,  `vswhere` also returns any prereleases/preview versions along with the release versions.
> 
> See doc: https://github.com/microsoft/vswhere/blob/f791b32483204ad3b0ff3cdce57a0c85ee119a8f/src/vswhere.lib/vswhere.lib.rc#L80
> 
> 
> 
> The current code defaults to the latest without user opt-in/choice if there are multiple versions. This change just extends it further to allow latest *Preview* versions as well. Note that without this change, if I just have VS Preview version installed (with valid MSVC compiler), ycmd build fails with the error that MSVC could not be found.

If I have both a released and pre-release version, which is picked?

2023-09-27 20:46 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711)* status: 0 of 2 LGTMs obtained (waiting on @sankhesh)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1711#-NfNO3w86OwB18rwbt8w:-NfNO3w91bzgqAykUiJk:b-pud9wf) (no related file):*
Flake8 error means ci is broken. Line too long. 

___


<!-- Sent from Reviewable.io -->

2023-10-03 13:22 UTC, sankhesh commented
> If I have both a released and pre-release version, which is picked?

I am not an expert but IMHO, because of the `-latest` flag, the later of the two versions will be picked i.e. between VS2019 Preview and VS 2022, the latter will be chosen.

> Flake8 error means ci is broken. Line too long.

Thanks, I'll fix that.

2023-10-03 18:59 UTC, bstaletic approved these changes
I am in favour of this. MS takes ages between two non-preview releases and I know that some people do use latest preview only. Plus MS likes to write blog posts about how latest preview versions are the bestest.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

@sankhesh Would you mind using reviewable for the review. It helps keep discussion threads in order and has some nice features.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711#-:-Nfpn2S51je21MXyIOOD:bcv5aqw)* status: 1 of 2 LGTMs obtained (waiting on @sankhesh)



<!-- Sent from Reviewable.io -->

2023-10-03 19:42 UTC, sankhesh reviewed
Sure :+1:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711#-:-Nfr26NC9Ec5oB5-mdH2:b-tt8ls0)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1711#-NfNO3w86OwB18rwbt8w:-Nfr11KF2YIzjXEZ-20X:b-896fix) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Flake8 error means ci is broken. Line too long.
</blockquote></details>

Done.

___
___
*[`build.py` line 129 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1711#-NfNJTH682ptyWAy7Yc4:-Nfr1F4YAYv3rhz7-KfN:bb6un1j) ([raw file](https://github.com/ycm-core/ycmd/blob/9c5317394360a6a258e79a29785a26eff588aa08/build.py#L129)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Please can you explain canonically what this does? We don’t want to always use prerelease versions. In fact I’d rather not support them at all as we will never test with them. I’m happy to make it work by chance or by opt-in, but not by default.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-06 20:32 UTC, sankhesh commented
Hmm.. I don't know why that CI is failing.

2023-10-06 21:14 UTC, bstaletic commented
It happens. Windows jobs are a little flakey.

2023-10-13 15:57 UTC, sankhesh commented
@bstaletic @puremourning Good to merge?

2023-10-13 16:49 UTC, bstaletic commented
I am ok with this pull request, but @puremourning said he would prefer this to be opt-in.

> I’m happy to make it work by chance or by opt-in, but not by default.

So could you add an option like `--preview-msvc` (or smothing, naming is hard) to the argument parser in `build.py`?

2023-12-01 20:33 UTC, sankhesh commented
@bstaletic @puremourning The latest commit adds the `--preview-msvc` option.

2023-12-12 20:34 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

thanks!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711#-:-NlUjJeP5k9tno_yBYoV:b-i7on7d)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @sankhesh)



<!-- Sent from Reviewable.io -->

2023-12-12 20:52 UTC, sankhesh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711#-:-NlUnBfu82ri1nsFEy94:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2023-12-12 20:56 UTC, sankhesh reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1711)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2023-12-22 18:07 UTC, sankhesh commented
@bstaletic @puremourning Anything else needed here?

2023-12-22 18:08 UTC, puremourning commented
> @bstaletic @puremourning Anything else needed here?

Well, CI is failing, so we will need to resolve that before merging.

2023-12-22 18:38 UTC, merged