Fix g:ycm_roslyn_binary_path being ignored
ycm-core/ycmd pull request #1721
Opened 2023-12-09 17:54 UTC by dkaszews

Fixes the `g:ycm_roslyn_binary_path` only being used in prechecks, and the actual server always being started from the `ycmd/third_party` directory.

Also fixes the `:YcmDebugInfo` printing the directory containing default OmniSharp executable (and not the executable file itself); now prints full command with arguments used to start the server.

2023-12-09 21:05 UTC, bstaletic requested changes
Functionally, this looks good.
I did leave one comment.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlFOV7--VMTbcEXf-_L:bqbdfag)* status: 0 of 2 LGTMs obtained (waiting on @dkaszews)

___
*[`ycmd/tests/cs/debug_info_test.py` line 207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NlFN9WW2hKR5Lbu1XeO:-NlFN9WW2hKR5Lbu1XeP:bewiifx) ([raw file](https://github.com/ycm-core/ycmd/blob/6ef84d38244a9e873fb49163e1a60bb0613ac4db/ycmd/tests/cs/debug_info_test.py#L207)):*
> ```Python
> 
> 
>   def _RoslynFromUserOption_popen_mock(*args, **kwargs):
> ```

This will fail flake8 check. 

`( *args, **kwargs )` - mind the "floating" parentheses.

Also, I'm too hungry to take a closer look now, but...

if this helper function needs to be a member of the test class, I would prefer to see `self, *args, **kwargs`.
If it needs not be a member of the test class, let's move it above the test class.


<!-- Sent from Reviewable.io -->

2023-12-09 21:36 UTC, dkaszews reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/tests/cs/debug_info_test.py` line 207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NlFN9WW2hKR5Lbu1XeO:-NlFUK-y57q1IrV-J9uN:b-h8j66h) ([raw file](https://github.com/ycm-core/ycmd/blob/6ef84d38244a9e873fb49163e1a60bb0613ac4db/ycmd/tests/cs/debug_info_test.py#L207)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This will fail flake8 check. 

`( *args, **kwargs )` - mind the "floating" parentheses.

Also, I'm too hungry to take a closer look now, but...

if this helper function needs to be a member of the test class, I would prefer to see `self, *args, **kwargs`.
If it needs not be a member of the test class, let's move it above the test class.
</blockquote></details>

It doesn't need to be member of test class, but I would like to keep it next to the test case as it has same hardcoded value, basically a multiline lambda. Maybe `@staticmethod` then?

I also just had a stupid idea to check out tommorow. We only care about value here and the forward to real `Popen` is just to keep rest of test of failing. Just throw some custom exception that will only be caught in test and end it early. Should save a lot of time by not actually starting the server and waiting on it. 


<!-- Sent from Reviewable.io -->

2023-12-09 21:40 UTC, dkaszews reviewed
.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlFWWLeB6Aog479MaWh:b3kqx)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2023-12-10 12:44 UTC, bstaletic commented
Also, we have merged the unicode/regex update, so you should rebase.

2023-12-10 19:37 UTC, dkaszews reviewed
Fixed and rebased

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlKE5PV509FbOO3xBww:bjyq7l2)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/tests/cs/debug_info_test.py` line 207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NlFN9WW2hKR5Lbu1XeO:-NlKDrsZCLPDhRFOKT2q:b-680by6) ([raw file](https://github.com/ycm-core/ycmd/blob/6ef84d38244a9e873fb49163e1a60bb0613ac4db/ycmd/tests/cs/debug_info_test.py#L207)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`@staticmethod` sounds good to me.
</blockquote></details>

Done, the exception idea unfortunatelly did not work, as it was caught by production code I don't have time to investigate.


<!-- Sent from Reviewable.io -->

2023-12-10 20:23 UTC, bstaletic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlKOTB91ZLKiNG70Zv7:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-10 20:31 UTC, bstaletic approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-10 22:30 UTC, dkaszews commented
Apparently `@patch` does not work with `@staticmethod` before Python 3.10 and CI uses 3.8. Wouldn't be an issue if stupid Python had multiline lambdas. Will have to look at alternative solutions.

2023-12-11 07:41 UTC, bstaletic reviewed
We can just drop `@staticmethod` and add a `self` as the first argument, which it would have anyway. Then just add a comment about it too.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlMo_Ve1F2UDcHBEvfu:b-pqbj1i)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-11 15:47 UTC, dkaszews commented
That did not work either, was getting errors that instance method was called without `self`. Found alternative of patching inside test with local function.

2023-12-12 20:05 UTC, puremourning requested changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)

___
*[`ycmd/tests/cs/debug_info_test.py` line 212 at r5](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NlUbZyu4Nb4PWoZKr7z:-NlUbZyu4Nb4PWoZKr8-:b-ayef89) ([raw file](https://github.com/ycm-core/ycmd/blob/d4fd0254a0b4f56ba0aa90ce54dba673b6748f94/ycmd/tests/cs/debug_info_test.py#L212)):*
> ```Python
>     # `@patch` does not play nice with functions defined at class scope
>     def _popen_mock( *args, **kwargs ):
>       assert_that( args[ 0 ][ 1 ], equal_to( 'my_roslyn.exe' ) )
> ```

given that we're using `args[0]` directly, why not:

```
def _popen_mock( cmdline, *args, **kwargs ):
    # use cmdline
```


<!-- Sent from Reviewable.io -->

2023-12-12 20:18 UTC, dkaszews reviewed
Applied suggestion

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlUfddv4gsfrFK2aSVL:bu9y4bw)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/tests/cs/debug_info_test.py` line 212 at r5](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NlUbZyu4Nb4PWoZKr7z:-NlUfUsO9pNQuGv6fgXt:b-116lpi) ([raw file](https://github.com/ycm-core/ycmd/blob/d4fd0254a0b4f56ba0aa90ce54dba673b6748f94/ycmd/tests/cs/debug_info_test.py#L212)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

given that we're using `args[0]` directly, why not:

```
def _popen_mock( cmdline, *args, **kwargs ):
    # use cmdline
```
</blockquote></details>

Fair point, done. I omitted `*args` because all other arguments are named-only.


<!-- Sent from Reviewable.io -->

2023-12-12 20:21 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NlUgDnC7tqfRDMem1bo:bnfp4nl)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-13 20:08 UTC, dkaszews commented
Any clue why this fails only on older Windows?

2023-12-21 16:55 UTC, puremourning commented
I have re-run them. Let's see if it was CI flake.

2023-12-21 17:35 UTC, puremourning commented
Nope, looks like the test really does just fail on windows:

```
======================================================================
ERROR: test_GetCompleter_RoslynFromUserOption (ycmd.tests.cs.debug_info_test.DebugInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\unittest\mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "D:\a\ycmd\ycmd\ycmd\tests\cs\__init__.py", line 70, in Wrapper
    test( test_case_instance, app, *args, **kwargs )
  File "D:\a\ycmd\ycmd\ycmd\tests\cs\debug_info_test.py", line 219, in test_GetCompleter_RoslynFromUserOption
    with WrapOmniSharpServer( app, filepath ):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\a\ycmd\ycmd\ycmd\tests\cs\__init__.py", line 108, in WrapOmniSharpServer
    GetDiagnostics( app, filepath )
  File "D:\a\ycmd\ycmd\ycmd\tests\cs\__init__.py", line 99, in GetDiagnostics
    return app.post_json( '/event_notification', event_data ).json
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\webtest\utils.py", line 34, in wrapper
    return self._gen_request(method, url, **kw)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\webtest\app.py", line 749, in _gen_request
    return self.do_request(req, status=status,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\webtest\app.py", line 646, in do_request
    self._check_status(status, res)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\webtest\app.py", line 675, in _check_status
    raise AppError(
webtest.app.AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/event_notification)
b'{"exception":{"TYPE":"AssertionError"},"message":"\\nExpected: \'my_roslyn.exe\'\\n     but: was \'-p\'\\n","traceback":"Traceback (most recent call last):\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\third_party\\\\bottle\\\\bottle.py\\", line 876, in _handle\\n    return route.call(**args)\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\third_party\\\\bottle\\\\bottle.py\\", line 1756, in wrapper\\n    rv = callback(*a, **ka)\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\handlers.py\\", line 65, in EventNotification\\n    response_data = getattr( _server_state.GetFiletypeCompleter( filetypes ),\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\completers\\\\cs\\\\cs_completer.py\\", line 262, in OnFileReadyToParse\\n    solutioncompleter._StartServer()\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\completers\\\\cs\\\\cs_completer.py\\", line 421, in _StartServer\\n    return self._StartServerNoLock()\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\completers\\\\cs\\\\cs_completer.py\\", line 466, in _StartServerNoLock\\n    self._omnisharp_phandle = utils.SafePopen(\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\utils.py\\", line 370, in SafePopen\\n    return subprocess.Popen( args, **kwargs )\\n  File \\"C:\\\\hostedtoolcache\\\\windows\\\\Python\\\\3.8.10\\\\x64\\\\lib\\\\unittest\\\\mock.py\\", line 1081, in __call__\\n    return self._mock_call(*args, **kwargs)\\n  File \\"C:\\\\hostedtoolcache\\\\windows\\\\Python\\\\3.8.10\\\\x64\\\\lib\\\\unittest\\\\mock.py\\", line 1085, in _mock_call\\n    return self._execute_mock_call(*args, **kwargs)\\n  File \\"C:\\\\hostedtoolcache\\\\windows\\\\Python\\\\3.8.10\\\\x64\\\\lib\\\\unittest\\\\mock.py\\", line 1155, in _execute_mock_call\\n    return self._mock_wraps(*args, **kwargs)\\n  File \\"D:\\\\a\\\\ycmd\\\\ycmd\\\\ycmd\\\\tests\\\\cs\\\\debug_info_test.py\\", line 212, in _popen_mock\\n    assert_that( cmdline[ 1 ], equal_to( \'my_roslyn.exe\' ) )\\n  File \\"C:\\\\hostedtoolcache\\\\windows\\\\Python\\\\3.8.10\\\\x64\\\\lib\\\\site-packages\\\\hamcrest\\\\core\\\\assert_that.py\\", line 58, in assert_that\\n    _assert_match(actual=actual_or_assertion, matcher=matcher, reason=reason)\\n  File \\"C:\\\\hostedtoolcache\\\\windows\\\\Python\\\\3.8.10\\\\x64\\\\lib\\\\site-packages\\\\hamcrest\\\\core\\\\assert_that.py\\", line 73, in _assert_match\\n    raise AssertionError(description)\\nAssertionError: \\nExpected: \'my_roslyn.exe\'\\n     but: was \'-p\'\\n\\n"}'
```

2023-12-21 17:40 UTC, dkaszews commented
Could not get through the callstack myself, but now it just looks like it fails because on Windows it runs with `my_roslyn.exe ...` instead of `mono my_roslyn.exe ...`. Easy enough fix, that's why I asked on gitter whether this test will run on Windows 🤷

2023-12-21 17:47 UTC, puremourning commented
yeah, it's a bit cryptic the way the failure is reported!

2023-12-21 19:04 UTC, puremourning requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 0 of 2 LGTMs obtained (and 2 stale) (waiting on @dkaszews)

___
*[`ycmd/tests/cs/debug_info_test.py` line 212 at r7](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NmCkieW2QxUv_1LsdIM:-NmCkieW2QxUv_1LsdIN:b19hmgg) ([raw file](https://github.com/ycm-core/ycmd/blob/bb69073303be41b5e0749ea0abae21e9b54ba5dc/ycmd/tests/cs/debug_info_test.py#L212)):*
> ```Python
>     # `@patch` does not play nice with functions defined at class scope
>     def _popen_mock( cmdline, **kwargs ):
>       i = cmdline[ 0 ].endswith( 'mono' )
> ```

not a fan of this. I would rather:

```
exe_idx = 1 if cmdline[ 0 ].endswith( 'mono' ) else 0
```

Because that says what it is doing, rather than assuming you implicitly know that, and that the True will turn into `1` when used as an index... which is weird.


<!-- Sent from Reviewable.io -->

2023-12-21 19:43 UTC, dkaszews reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 0 of 2 LGTMs obtained (and 2 stale) (waiting on @puremourning)

___
*[`ycmd/tests/cs/debug_info_test.py` line 212 at r7](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NmCkieW2QxUv_1LsdIM:-NmCtkdl3njlKrWMYtcm:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/bb69073303be41b5e0749ea0abae21e9b54ba5dc/ycmd/tests/cs/debug_info_test.py#L212)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

not a fan of this. I would rather:

```
exe_idx = 1 if cmdline[ 0 ].endswith( 'mono' ) else 0
```

Because that says what it is doing, rather than assuming you implicitly know that, and that the True will turn into `1` when used as an index... which is weird.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-22 16:37 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Let's squash.

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NmHNx8o0hfTkL2Kjzl1:bupiep1)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)

___
*[`-- commits` line 28 at r9](https://reviewable.io/reviews/ycm-core/ycmd/1721#-NmHNqzi7o_BYE_jk2T_):*
let's squash the commits now, LGTM.


<!-- Sent from Reviewable.io -->

2023-12-22 16:38 UTC, puremourning reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-23 21:56 UTC, dkaszews commented
@puremourning Do you need me to squash manually? I'm AFK so might be a bit hard.

The codecov fails seem to be because I rewrote bits of code to be shorter so the line percentage went down 🙄

2023-12-24 13:44 UTC, puremourning commented
@mergifyio squash

2023-12-26 06:12 UTC, bstaletic reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

@dkaszews Thanks for the pull request!

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-NmZkAiZ08MQqcsl4s5B:b-eogdb)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-27 16:23 UTC, puremourning reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721#-:-Nmg4i1ZD9VDXnBGFbie:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-27 16:24 UTC, puremourning reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1721)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained (waiting on @dkaszews)



<!-- Sent from Reviewable.io -->

2023-12-27 16:24 UTC, merged