Sort diagnostics according to severity for detailed diag responses
ycm-core/ycmd pull request #1728
Opened 2024-01-14 09:33 UTC by bstaletic

Users are more likely to be interested in errors than warnings in /detailed_diagnostic responses. That means we need to sort the diagnostics before finding the one nearest to the cursor.

For LSP completers, that's easy as the severity is numerical. For Omnisharp-roslyn and TSServer, the severity is a word and we can't just say `sort( key = severity )`.

Since LSP severity was convenient for comparison, I have opted for sorting C# and TS diags by the equivalent LSP severity.

2024-01-14 10:57 UTC, bstaletic commented
According to the coverage data, we're only ever dealing with errors in our tests, at least for C# and TS.

2024-01-14 14:41 UTC, puremourning reviewed
Change LGTM, but could we at least add a regression test for LSP ? Seems like something that we could easily forget about.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728#-:-No7Pi0hEgwbwCJ-1jaA:bge8cyc)* status: 0 of 2 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-14 14:41 UTC, puremourning approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2024-01-14 14:46 UTC, bstaletic reviewed
I wanted to, but I couldn't make a test case without pulling in the entirety of ranges-v3. That just feels like a massive dependency for our need.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728#-:-No7QrD5DPE4bsW0g-iT:b5t3wfj)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2024-01-14 14:49 UTC, puremourning commented
Don't we just need some code which produces a warning and error on the same line.

I think clangd does this. maybe something like:

```
int x;
if ( x = 2 )
{
}
```

With `-Wno-error -Werror=uninitialized`

2024-01-15 10:39 UTC, bstaletic reviewed
Tests added.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728#-:-NoBh4Ez0FoZPuftk8c4:b-wj4ea6)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)



<!-- Sent from Reviewable.io -->

2024-02-14 16:45 UTC, puremourning requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/completers/language_server/language_server_completer.py` line 1666 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1728#-NqcV-t06HAgy07GJewQ:-NqcV-t06HAgy07GJewR:bhlzhr5) ([raw file](https://github.com/ycm-core/ycmd/blob/b5d1e22d777afa60b9fc501c4ca6eb0d3ef90844/ycmd/completers/language_server/language_server_completer.py#L1666)):*
> ```Python
>     current_column = lsp.CodepointsToUTF16CodeUnits(
>         GetFileLines( request_data, current_file )[ current_line_lsp ],
>         request_data[ 'column_codepoint' ] - 1 )
> ```

I'm not sure about this.... 


the help doc for this func says the offset is in 1-based units:

```
def CodepointsToUTF16CodeUnits( line_value, codepoint_offset ):
  """Return the 1-based UTF-16 code unit offset equivalent to the 1-based
  unicode codepoint offset |codepoint_offset| in the Unicode string
  |line_value|"""
```

If `current_column` is `0-based` then we should subtract 1 from the result of the call, not the input.


<!-- Sent from Reviewable.io -->

2024-02-15 03:28 UTC, bstaletic reviewed
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[`ycmd/completers/language_server/language_server_completer.py` line 1666 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1728#-NqcV-t06HAgy07GJewQ:-NqemSvz-PJZRzP9lFre:b8sp355) ([raw file](https://github.com/ycm-core/ycmd/blob/b5d1e22d777afa60b9fc501c4ca6eb0d3ef90844/ycmd/completers/language_server/language_server_completer.py#L1666)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I'm not sure about this.... 


the help doc for this func says the offset is in 1-based units:

```
def CodepointsToUTF16CodeUnits( line_value, codepoint_offset ):
  """Return the 1-based UTF-16 code unit offset equivalent to the 1-based
  unicode codepoint offset |codepoint_offset| in the Unicode string
  |line_value|"""
```

If `current_column` is `0-based` then we should subtract 1 from the result of the call, not the input.
</blockquote></details>

Without the `-1`, `current_column` is 1-based.
However, we are coparing that column to `diagnostic[ 'range' ]`, later in the for loop, where diagnostics have 0-based character offsets. The comment I added above the call to `CodepointsToUTF16CodeUnits()` should explain that.

I remember going back and forward and not being sure if that `-1` should go before of after `)` of the function call.

Thanks for catching this! Fixed.


<!-- Sent from Reviewable.io -->

2024-02-17 12:26 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1728#-:-Nqr1-yV9zt_Gli8AQ5F:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)



<!-- Sent from Reviewable.io -->

2024-02-17 13:26 UTC, merged